trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.19

jobs:
- template: job--pre-commit.yml@asottile
- template: job--go-test.yml@asottile
  parameters:
    go_versions: ['1.11.5', '1.12']
    os: 'linux'
    tests: '.'  # only test the top level
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27]
    os: linux
    name_postfix: _go_1_11
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.11'
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37]
    os: linux
    name_postfix: _go_1_12
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.12'
